name: bd_app_v0
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  fpdart: ^1.2.0
  go_router: ^16.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/areas/
    - assets/images/cards/
    - assets/images/header/
    - assets/images/onboarding/
    - assets/logo/
